version: "3.8"

services:
  api:
    build:
      context: ../..
      dockerfile: config/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../app:/app/app
      - ../../tests:/app/tests
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 