services:
  # Development service - also used for testing
  dev:
    build:
      context: .
      dockerfile: config/dev/Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./src:/app/src
      - ./app:/app/app
      - ./public:/app/public
      - ./__tests__:/app/__tests__
      - ./__mocks__:/app/__mocks__
      - ./jest.config.js:/app/jest.config.js
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000/api
      - ENABLE_DEBUG=true
      - APP_ENV=dev
    depends_on:
      - api-dev
    networks:
      - lifeflow-network

  # Gamma (staging) service
  gamma:
    build:
      context: .
      dockerfile: config/gamma/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://gamma-api.lifeflow.app/api
      - ENABLE_DEBUG=true
      - APP_ENV=gamma
    networks:
      - lifeflow-network

  # Production service
  prod:
    build:
      context: .
      dockerfile: config/prod/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://api.lifeflow.app/api
      - ENABLE_DEBUG=false
      - APP_ENV=production
    networks:
      - lifeflow-network

  # Mock API for development
  api-dev:
    image: node:18-alpine
    working_dir: /api
    volumes:
      - ../backend:/api
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - lifeflow-network

networks:
  lifeflow-network:
    driver: bridge 