name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd backend && pip3 install -r config/dev/requirements.txt

      - name: Check formatting with Black
        run: cd backend && black --check app

      - name: Check imports with isort
        run: cd backend && isort --check-only app

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd backend && pip3 install -r config/dev/requirements.txt

      - name: Run tests
        run: cd backend && pytest

  build-and-push:
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [gamma, prod]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/config/${{ matrix.environment }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lifeflow:${{ matrix.environment }}
